version: 2
jobs:
  first_job:
    docker:
      - image: alpine:3.7
    steps:
      - run: 
          name: "Declare the variable"
          command: |
            echo 'export MYNEWVAR="Value of my new variable"' >> $BASH_ENV
            source $BASH_ENV
            echo $MYNEWVAR
      - run:
          name: "Save the variable"
          command: |
            cat $BASH_ENV
            mkdir output
            cat $BASH_ENV > output/file
      - run:
          name: "Install the certificate"
          command: |
             apk add ca-certificates
      - persist_to_workspace:
          root: output
          paths: 
            file
            
  second_job:
    docker:
      - image: alpine:3.7
    steps:
      - attach_workspace:
          at: output
      - run:
          name: "Check MYNEWVAR's value and the context variable's value"
          command: |  
            cat output/file > $BASH_ENV
            source $BASH_ENV
            echo $MYNEWVAR
      - run: 
          name: "Check the variable one more time"
          command: |
            echo $MYNEWVAR
            cat $BASH_ENV
      
workflows:
  version: 2
  "Variables test":
    jobs:
      - first_job
      - second_job:
          requires:
            - first_job
